version: '3'
services:
  app:
    image: node:latest
    environment:
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src/backend:/app
    working_dir: /app
    command: npm run start
